spring:
  application:
    name: subway-ticket-backend
  autoconfigure:
    exclude: []
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/subway_ticket_system?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    hikari:
      maximum-pool-size: 5
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
